---
name: Deploy app
hosts: work_group
become: yes
tasks:
  - name: deploy the app
    docker_container:
      name: myapp-container
      image: myapp:latest
      state: started
      ports:
        - "8083:80"