pipeline{

agent  any

triggers {
    githubPush()
}

environment{
    Docker_Image = "myapp:latest"
}

stages{

stage('ClonetheRepo'){
    steps{
     git 'https://github.com/ThakshalaMadhuwanthi/SampleProjectDeployment.git'
    }



}
stage('BuildImage'){

    steps{
     bat 'docker build -t $Docker_Image .'
    }
   
}

stage('DeployWithAnsible'){
    steps{
        bat 'ansible-playbook -i ansible/inventory deploy.yml'
    }
}



}

post{
    success{
        echo 'Successfully Deployed!'
    }
    failure{
        echo 'Deplyment failed!'
    }
}



}