pipeline{

agent  any

triggers {
    githubPush()
}

environment{
    Docker_Image = "myapp:latest"
}

stages{





stage('BuildImage'){

    steps{
     bat 'docker build -t %Docker_Image%  project/'
    }
   
}

stage('DeployWithAnsible'){
    steps {
        bat 'wsl   ansible-playbook -i /mnt/d/Jenkins/.jenkins/workspace/SampleDeployment/project/ansible/inventory /mnt/d/Jenkins/.jenkins/workspace/SampleDeployment/project/ansible/deploy.yml'
    }
}



}

post{
    success{
        echo 'Successfully Deployed!'
    }
    failure{
        echo 'Deplyment failed!'
    }
}



}